### ISSUE TITLE
General comments about the project

### ISSUE THREAD

**Issue by davidauza-engineer** [hugopassos/sample_app#15]
Leaving some comments about your project:

- It's good that you make some tests for all of the methods, that way you can ensure that everything works very good.

- Good job on creating some comments for your methods, that way your code is easier to understand while reading it.

**Comment by evaveskova** [comment]
Great job Hugo! I'd recommend in the future to name your test files with "spec" instead of "test." Eg. "sessions_controller_spec.rb" instead of "sessions_controller_test.rb."
Besides that everything looks great.
